### ISSUE TITLE
Is this project still active and valid?

### ISSUE THREAD

**Issue by jonstorer-sfmc** [nspec/NSpec.VsAdapter#12]
Last update is Jan 5, 2018

**Comment by BrainCrumbz** [comment]
Hi @jonstorer-sfmc ,
we've been involved as contributors into NSpec library and NSpec.VsAdapter, but currently we're not working on this. There were some impacting changes in Visual Studio testing framework and its API (I think there are issues opened describing that, whether here or in NSpec progject).  
Once those changes settled, this adapter was supposed to be upgraded, as well as (possibly) the library itself.

So here's the current state of things. If you feel like working on this to get the tool at a point that satisfy you, please feel free to comment on that.

Also, something to always keep in ming: NSpec testing library does not force into using a VS adapter. One might create an executable runner project that will perform all tests written and show results in command line. This feature is described in NSpec documentation and in some issues as well.

**Comment by jonstorer-sfmc** [comment]
@BrainCrumbz Thanks for getting back to me. I'm new to the .NET world and was looking for libraries similar to where I'm coming from. I'm not quiet ready to commit to OSS libraries just yet. Plus, my goal is to learn this languages how-to's before making changes. 

Thanks!
